### ISSUE TITLE
Using URLs to refer to large keys

### ISSUE THREAD

**Issue by keks** [mailencrypt/inbome#10]
Large keys don't fit into the mail header so there was the idea of instead using a URL that refers to the public key. This means that suddenly we rely on infrastructure completely outside our control so we should make sure the keys integrity is secured.
This can be done by providing the hash of the key in the header.

Also we could provide the details needed to pin the certificate of the server that serves the key.

**Comment by azul** [comment]
We are currently tending to delegate people to the OpenPGP header if they want to do fancy stuff with other keys than the standard INBOME ones.
There you can already specify urls, fingerprints and the like.

**Comment by keks** [comment]
Seems like the "too large for mail header" topic is a non-issue atm so we don't need URLs anyway. Closing for now.
