### ISSUE TITLE
Setup inbome test-bot for MUA developers and users 

### ISSUE THREAD

**Issue by hpk42** [mailencrypt/inbome#12]
would be great to have an inbome test web service for example at  https://inbome-test.net  which allows MUA developers and users to test out their INBOME functionality.  How it works:

- user enters email into input email
- web service triggers creation of INBOME key etc + sending a mail to that user:
```
    From: 1129837123kkkk2873@inbome-test.net
    To: some@example.org
    INBOME-Encryption: ....
```
- Then the user checks his inbox to see if the MUA parses the INBOME
  header correctly, adds own INBOME header and replies encrypted.

- the webservice receives encrypted mail and replies encrypt
  and shows something on the webpage

**Comment by varac** [comment]
We setup a test server running a bot that will reply to mails containing an `INBOME-ENCRYPT` header soon.

for development, ssh into:

     ssh bot@mail.autocrypt.org

    ECDSA key fingerprint is SHA256:4RWh81zOd/Pgq3mHhKpyLdVZJfOpq+DgqKheUIhJgWQ

When the script is up, just send a mail to `bot@mail.autocrypt.org`.
Postfix will pipe this through a python script, which will parse the inbome headers and reply on success.

**Comment by varac** [comment]
works now. Please test!

**Comment by varac** [comment]
## Todo

- [x] RDNS for mail.autocrypt.org
- [ ] whitelist local recipients @autocrypt.org
- [x] Configure dovecot

**Comment by varac** [comment]
Imap is setup, please see my mail from today how to use it.
