### ISSUE TITLE
Disaster Recovery

### ISSUE THREAD

**Issue by Valodim** [mailencrypt/inbome#4]
People lose devices, people forget passwords. Some scenarios and thoughts:

* Device is lost, no precautions at all

This is a bad case, because it leaves us with
a) unreadable mail, forever
b) more unreadable mail from peers with established INBOME negotiation

Not much we can do here I guess, other than regenerate and hope the user doesn't abandon crypto? I'm not sure "send mail to all users we established crypto with" is such a good idea... We should avoid this scenario by all possible means!

* Device is lost, no backup

In this case, the issue a) is a lost cause by design. We can help issue b) along if we were able to store a revocation certificate somewhere along the way.

Revocation certificates are not of very high value (they only help for denial of service attacker capability, and that's achievable without them), so we can store them in the user's mailbox in plaintext, then publish it when we regenerate keys. This requires a distribution mechanism of course, which is solved in pgp using keyservers, *if* we can assume everyone to update keys every few days, or before use.

* Device is lost, but there is a backup

This is the scenario we should try to be in. So we should automate, as much as possible!

General idea: Make a backup of secret key material in the user's mailbox, which is encrypted with a high-entropy backup code that is left with the user. (see [relevant document](https://github.com/mailencrypt/inbome/blob/master/doc/multi-device.rst))

(Just brainstorming: Another possible option would be to hand the user the random seed used for generating all key material, so we wouldn't even need to store anything ("offline backup"). But that is a dangerous route, requires a deterministic PRNG implementation on all platforms, and is also something we can only do at key setup)

**Comment by dkg** [comment]
We should track this now at https://github.com/autocrypt/autocrypt/issues/2
